//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKRS.Galaxy2.Dispense {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AKRS.Galaxy2.Dispense.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加点 的本地化字符串。
        /// </summary>
        internal static string ACTION_APPEND_POINT {
            get {
                return ResourceManager.GetString("ACTION_APPEND_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除点 的本地化字符串。
        /// </summary>
        internal static string ACTION_DELETE_POINT {
            get {
                return ResourceManager.GetString("ACTION_DELETE_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入点 的本地化字符串。
        /// </summary>
        internal static string ACTION_INSERT_POINT {
            get {
                return ResourceManager.GetString("ACTION_INSERT_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动点 的本地化字符串。
        /// </summary>
        internal static string ACTION_MOVE_POINT {
            get {
                return ResourceManager.GetString("ACTION_MOVE_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加曲线 的本地化字符串。
        /// </summary>
        internal static string ACTION_PAINT_CURVE {
            get {
                return ResourceManager.GetString("ACTION_PAINT_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转背景图片 的本地化字符串。
        /// </summary>
        internal static string ACTION_ROTATE_BACKGROUND_IMAGE {
            get {
                return ResourceManager.GetString("ACTION_ROTATE_BACKGROUND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转曲线 的本地化字符串。
        /// </summary>
        internal static string ACTION_ROTATE_CURVE {
            get {
                return ResourceManager.GetString("ACTION_ROTATE_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放曲线 的本地化字符串。
        /// </summary>
        internal static string ACTION_SCALE_CURVE {
            get {
                return ResourceManager.GetString("ACTION_SCALE_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string ACTION_SELECT_OBJECT {
            get {
                return ResourceManager.GetString("ACTION_SELECT_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移背景图片 的本地化字符串。
        /// </summary>
        internal static string ACTION_TRANSLATE_BACKGROUND_IMAGE {
            get {
                return ResourceManager.GetString("ACTION_TRANSLATE_BACKGROUND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移曲线 的本地化字符串。
        /// </summary>
        internal static string ACTION_TRANSLATE_CURVE {
            get {
                return ResourceManager.GetString("ACTION_TRANSLATE_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画胶样式 的本地化字符串。
        /// </summary>
        internal static string FORM_TITLE {
            get {
                return ResourceManager.GetString("FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}um × {1}um 的本地化字符串。
        /// </summary>
        internal static string FORMAT_DIE_SIZE {
            get {
                return ResourceManager.GetString("FORMAT_DIE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}(um/pixel) 的本地化字符串。
        /// </summary>
        internal static string FORMAT_MICRON_PER_PIXEL {
            get {
                return ResourceManager.GetString("FORMAT_MICRON_PER_PIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调取失败。 的本地化字符串。
        /// </summary>
        internal static string MESSAGE_BOX_TEXT_RETRIEVE_PATTERN_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TEXT_RETRIEVE_PATTERN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        internal static string NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点 的本地化字符串。
        /// </summary>
        internal static string POINT_ROLE_END {
            get {
                return ResourceManager.GetString("POINT_ROLE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点 的本地化字符串。
        /// </summary>
        internal static string POINT_ROLE_START {
            get {
                return ResourceManager.GetString("POINT_ROLE_START", resourceCulture);
            }
        }
    }
}
